### ISSUE TITLE
Bug when starting a lab with X11

### ISSUE THREAD

**Issue by IlyesBenighil** [mfthomps/Labtainers#60]
When i'm starting a lab with X11 (i'm on an WSL2 ubuntu system)  I have this error : 

`Exception in thread gdblesson:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ilyes/labtainers/labtainer/trunk/scripts/labtainer-student/bin/labutils.py", line 1282, in DoStartOne
    display_num = int(float(display))
ValueError: could not convert string to float: '72.30.192.1:0.0'`

In labutils.py line 1282, there is 
`display_num = int(float(display[1:]))`
I'm not sure but display_num should be '0.0'
I had to modify it by hand

**Comment by mfthomps** [comment]
Thanks for the report. It looks like that code is failing to anticipate a
full ip address as the display value.  I'll post a fix soon.
